name: Build and Release CLI

on:
  workflow_dispatch: # Allows manual triggering
  push:
    tags:
      - 'v*.*.*' # Trigger on new tags for formal releases

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        include:
          - goos: darwin
            goarch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: |
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o fasting-cli-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Archive for Linux/macOS
      if: matrix.goos != 'windows'
      run: |
        tar -czf fasting-cli-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz fasting-cli-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Archive for Windows
      if: matrix.goos == 'windows'
      run: |
        zip fasting-cli-${{ matrix.goos }}-${{ matrix.goarch }}.zip fasting-cli-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fasting-cli-${{ matrix.goos }}-${{ matrix.goarch }}
        path: fasting-cli-${{ matrix.goos }}-${{ matrix.goarch }}.*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download all workflow artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/**/*
        generate_release_notes: true
